name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: 
        pm2 list
        pm2 stop 2iam-server
        npm install
        npm run build
        pm2 start 2iam-server
        pm2 save
        sudo service nginx restart